apiVersion: v1
kind: Service
metadata:
  name: demand-pay
  namespace: prod
spec:
  selector:
    app: demand-pay
    tier: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demand-pay-deployment
  namespace: prod
spec:
  replicas: 1
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 0
     maxSurge: 1
  selector: 
    matchLabels:
      app: demand-pay
      tier: backend
  template:
    metadata:
      labels:
        app: demand-pay
        tier: backend
      namespace: prod
    spec:
      containers:
        - name: demand-pay
          image: REPO:TAG
          envFrom:
            - secretRef:
                name: demand-pay-secret
            - configMapRef:
                name: demand-pay-config
          resources:
            requests:
              cpu: 200m
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9080
            initialDelaySeconds: 60
            periodSeconds: 10