apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datapv
  namespace: dev
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources: 
    requests:
      storage: 10Gi