apiVersion: v1
kind: Service
metadata:
  name: bb-btc
  namespace: dev
spec:
  selector:
    app: bb-btc
    tier: blockbook
  type: NodePort
  ports:
    - protocol: TCP
      port: 9130
      targetPort: 9130

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-btc-deployment
  namespace: dev
spec:
  replicas: 1
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 0
     maxSurge: 1
  selector: 
    matchLabels:
      app: bb-btc
      tier: blockbook
  template:
    metadata:
      labels:
        app: bb-btc
        tier: blockbook
      namespace: dev
    spec:
      containers:
        - name: bb-btc
          image: REPO:TAG
          envFrom:
            #- secretRef:
                #name: bb-btc-secret
            #- configMapRef:
                #name: bb-btc-config
          volumeMounts:
            - name: datapv-bb-btc
              mountPath: /opt/coins/blockbook/bitcoin/data
          resources:
            requests:
              cpu: 200m
              memory: "512Mi"
          #readinessProbe:
            #httpGet:
              #path: /
              #port: 9130
            #initialDelaySeconds: 60
            #periodSeconds: 10    
      volumes:
        - name: datapv-bb-btc
          persistentVolumeClaim:
            claimName: datapv-bb-btc