apiVersion: v1
kind: Service
metadata:
  name: bitcoind
  namespace: dev
spec:
  selector:
    app: bitcoind
    tier: blockbook
  type: NodePort
  ports:
    - protocol: TCP
      port: 8332
      targetPort: 8332

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoind-deployment
  namespace: dev
spec:
  replicas: 1
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 0
     maxSurge: 1
  selector: 
    matchLabels:
      app: bitcoind
      tier: blockbook
  template:
    metadata:
      labels:
        app: bitcoind
        tier: blockbook
      namespace: dev
    spec:
      containers:
        - name: bitcoind
          #image: kylemanna/bitcoind:latest
          image: kylemanna/bitcoind@sha256:17c7dd21690f3be34630db7389d2f0bff14649e27a964afef03806a6d631e0f1
          envFrom:
            - secretRef:
                name: bitcoind-secret
            - configMapRef:
                name: bitcoind-config
          volumeMounts:
            - name: pvc-bitcoind
              mountPath: /bitcoin/.bitcoin
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
          #readinessProbe:
            #httpGet:
              #path: /
              #port: 9130
            #initialDelaySeconds: 60
            #periodSeconds: 10    
      volumes:
        - name: pvc-bitcoind
          persistentVolumeClaim:
            claimName: datapvc-bitcoind