apiVersion: v1
kind: Secret
metadata:
  name: bitcoind-secret
  labels:
    app: bitcoind
    tier: blockbook
  namespace: dev
data:
  rpcpassword: "ODB2RFVCWFZNUzR6SDRaK0tqbUJRdWhLZWZzaDBxTnJCdk00RytyeTAvNA=="